@echo off 
color 30 
echo.
echo       ===========================================
echo       =                                         =
echo       =         Bienvenido Ivan Sanchez         =
echo       =                                         =
echo       ===========================================
echo. 
echo.
echo Iniciando Servidor de Archivos Personales
pause
echo.
echo 10 porciento
echo 20 porciento
echo 30 porciento
echo 40 porciento
echo 50 porciento
echo 60 porciento
echo 70 porciento
echo 80 porciento
echo 90 porciento
echo 100 porciento
color 20
echo.
echo La configuracion ha sido cargada exitosamente
echo.
pause
echo.
cls
color 0F
echo ----------------------------- ELECUTANDO SERVIDOR -----------------------------
echo.
sails lift --silly
echo.
echo.
echo.
echo.
echo.
echo.
echo Presione una tecla para salir... 
pause>nul 
exit